---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: cyberbruhvtbbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyberbruhvtbbackend
  template:
    metadata:
      labels:
        app: cyberbruhvtbbackend 
    spec:
      containers:
        - name: cyberbruhvtbbackend
          image: vtbbackend
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          # ports:
          # - containerPort: 80
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      containers:
        - name: nginx 
          image: nginx:1.21-alpine
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          # ports:
          # - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d
