apiVersion : apps/v1
kind: Deployment
metadata:
  name: cyberbruhvtbbackend 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyberbruhvtbbackend
  template:
    metadata:
      labels:
        app: cyberbruhvtbbackend 
    spec:
      containers:
        - name: cyberbruhvtbbackend 
          image: vtbhackathon.azurecr.io/cyberbruhvtbbackend
          ports:
          - containerPort: 80